services: 
  mysql: 
    container_name: ContainerBD
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vortex
    volumes: 
      - ./init-scripts:/docker-entrypoint-init.sql
    ports:
      - "3307:3306" 

  site:
    container_name: VortexInstitucional
    image: janazi1/vortex:v1
    restart: always 
    ports:
      - "3333:3333"
